@extends('layouts.admin')

@section('content')
    <div class="container-fluid mt-4">
        <div class="row justify-content-center">
            <h2>Edit {{ $type->name }}</h2>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
        </div>
        <div class="row">
            <form action="{{ route('admin.types.update', $type) }}" method="POST">
                @csrf
                @method('PUT')
                {{-- name description --}}
                <div class="mb-3">
                    <label for="name" class="form-label">name</label>
                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name"
                        name="name" value="{{ old('name') ?? $type->name }}">
                    @error('name')
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="description" class="form-label">description</label>
                    <input type="text" class="form-control @error('description') is-invalid @enderror" id="description"
                        name="description" value="{{ old('description') ?? $type->description }}">
                    @error('description')
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="icon" class="form-label">icon</label>
                    <select class="form-select @error('icon') is-invalid @enderror" id="icon" name="icon">
                        <option value="{{ old('icon') ?? $type->icon }}" selected>{{ old('icon') ?? $type->icon }}</option>
                        <option value="fa-solid fa-align-right">&#xf038; fa-align-right</option>
                        <option value="fa-solid fa-amazon">&#xf270; fa-amazon</option>
                        <option value="fa-solid fa-ambulance">&#xf0f9; fa-ambulance</option>
                        <option value="fa-solid fa-anchor">&#xf13d; fa-anchor</option>
                        <option value="fa-solid fa-android">&#xf17b; fa-android</option>
                        <option value="fa-solid fa-angellist">&#xf209; fa-angellist</option>
                        <option value="fa-solid fa-angle-double-down">&#xf103; fa-angle-double-down</option>
                        <option value="fa-solid fa-angle-double-left">&#xf100; fa-angle-double-left</option>
                        <option value="fa-solid fa-angle-double-right">&#xf101; fa-angle-double-right</option>
                        <option value="fa-solid fa-angle-double-up">&#xf102; fa-angle-double-up</option>
                        <option value="fa-solid fa-angle-left">&#xf104; fa-angle-left</option>
                        <option value="fa-solid fa-angle-right">&#xf105; fa-angle-right</option>
                        <option value="fa-solid fa-angle-up">&#xf106; fa-angle-up</option>
                        <option value="fa-solid fa-apple">&#xf179; fa-apple</option>
                        <option value="fa-solid fa-archive">&#xf187; fa-archive</option>
                        <option value="fa-solid fa-area-chart">&#xf1fe; fa-area-chart</option>
                        <option value="fa-solid fa-arrow-circle-down">&#xf0ab; fa-arrow-circle-down</option>
                        <option value="fa-solid fa-arrow-circle-left">&#xf0a8; fa-arrow-circle-left</option>
                        <option value="fa-solid fa-arrow-circle-o-down">&#xf01a; fa-arrow-circle-o-down</option>
                        <option value="fa-solid fa-arrow-circle-o-left">&#xf190; fa-arrow-circle-o-left</option>
                        <option value="fa-solid fa-arrow-circle-o-right">&#xf18e; fa-arrow-circle-o-right</option>
                        <option value="fa-solid fa-arrow-circle-o-up">&#xf01b; fa-arrow-circle-o-up</option>
                        <option value="fa-solid fa-arrow-circle-right">&#xf0a9; fa-arrow-circle-right</option>
                        <option value="fa-solid fa-arrow-circle-up">&#xf0aa; fa-arrow-circle-up</option>
                        <option value="fa-solid fa-arrow-down">&#xf063; fa-arrow-down</option>
                        <option value="fa-solid fa-arrow-left">&#xf060; fa-arrow-left</option>
                        <option value="fa-solid fa-arrow-right">&#xf061; fa-arrow-right</option>
                        <option value="fa-solid fa-arrow-up">&#xf062; fa-arrow-up</option>
                        <option value="fa-solid fa-arrows">&#xf047; fa-arrows</option>
                        <option value="fa-solid fa-arrows-alt">&#xf0b2; fa-arrows-alt</option>
                        <option value="fa-solid fa-arrows-h">&#xf07e; fa-arrows-h</option>
                        <option value="fa-solid fa-arrows-v">&#xf07d; fa-arrows-v</option>
                        <option value="fa-solid fa-asterisk">&#xf069; fa-asterisk</option>
                        <option value="fa-solid fa-at">&#xf1fa; fa-at</option>
                        <option value="fa-solid fa-automobile">&#xf1b9; fa-automobile</option>
                        <option value="fa-solid fa-backward">&#xf04a; fa-backward</option>
                        <option value="fa-solid fa-balance-scale">&#xf24e; fa-balance-scale</option>
                        <option value="fa-solid fa-ban">&#xf05e; fa-ban</option>
                        <option value="fa-solid fa-bank">&#xf19c; fa-bank</option>
                        <option value="fa-solid fa-bar-chart">&#xf080; fa-bar-chart</option>
                        <option value="fa-solid fa-bar-chart-o">&#xf080; fa-bar-chart-o</option>
                        <option value="fa-solid fa-battery-full">&#xf240; fa-battery-full</option>
                        <option value="fa-solid fa-beer">&#xf0fc; fa-beer</option>
                        <option value="fa-solid fa-behance">&#xf1b4; fa-behance</option>
                        <option value="fa-solid fa-behance-square">&#xf1b5; fa-behance-square</option>
                        <option value="fa-solid fa-bell">&#xf0f3; fa-bell</option>
                        <option value="fa-solid fa-bell-o">&#xf0a2; fa-bell-o</option>
                        <option value="fa-solid fa-bell-slash">&#xf1f6; fa-bell-slash</option>
                        <option value="fa-solid fa-bell-slash-o">&#xf1f7; fa-bell-slash-o</option>
                        <option value="fa-solid fa-bicycle">&#xf206; fa-bicycle</option>
                        <option value="fa-solid fa-binoculars">&#xf1e5; fa-binoculars</option>
                        <option value="fa-solid fa-birthday-cake">&#xf1fd; fa-birthday-cake</option>
                        <option value="fa-solid fa-bitbucket">&#xf171; fa-bitbucket</option>
                        <option value="fa-solid fa-bitbucket-square">&#xf172; fa-bitbucket-square</option>
                        <option value="fa-solid fa-bitcoin">&#xf15a; fa-bitcoin</option>
                        <option value="fa-solid fa-black-tie">&#xf27e; fa-black-tie</option>
                        <option value="fa-solid fa-bold">&#xf032; fa-bold</option>
                        <option value="fa-solid fa-bolt">&#xf0e7; fa-bolt</option>
                        <option value="fa-solid fa-bomb">&#xf1e2; fa-bomb</option>
                        <option value="fa-solid fa-book">&#xf02d; fa-book</option>
                        <option value="fa-solid fa-bookmark">&#xf02e; fa-bookmark</option>
                        <option value="fa-solid fa-bookmark-o">&#xf097; fa-bookmark-o</option>
                        <option value="fa-solid fa-briefcase">&#xf0b1; fa-briefcase</option>
                        <option value="fa-solid fa-btc">&#xf15a; fa-btc</option>
                        <option value="fa-solid fa-bug">&#xf188; fa-bug</option>
                        <option value="fa-solid fa-building">&#xf1ad; fa-building</option>
                        <option value="fa-solid fa-building-o">&#xf0f7; fa-building-o</option>
                        <option value="fa-solid fa-bullhorn">&#xf0a1; fa-bullhorn</option>
                        <option value="fa-solid fa-bullseye">&#xf140; fa-bullseye</option>
                        <option value="fa-solid fa-bus">&#xf207; fa-bus</option>
                        <option value="fa-solid fa-cab">&#xf1ba; fa-cab</option>
                        <option value="fa-solid fa-calendar">&#xf073; fa-calendar</option>
                        <option value="fa-solid fa-camera">&#xf030; fa-camera</option>
                        <option value="fa-solid fa-car">&#xf1b9; fa-car</option>
                        <option value="fa-solid fa-caret-up">&#xf0d8; fa-caret-up</option>
                        <option value="fa-solid fa-cart-plus">&#xf217; fa-cart-plus</option>
                        <option value="fa-solid fa-cc">&#xf20a; fa-cc</option>
                        <option value="fa-solid fa-cc-amex">&#xf1f3; fa-cc-amex</option>
                        <option value="fa-solid fa-cc-jcb">&#xf24b; fa-cc-jcb</option>
                        <option value="fa-solid fa-cc-paypal">&#xf1f4; fa-cc-paypal</option>
                        <option value="fa-solid fa-cc-stripe">&#xf1f5; fa-cc-stripe</option>
                        <option value="fa-solid fa-cc-visa">&#xf1f0; fa-cc-visa</option>
                        <option value="fa-solid fa-chain">&#xf0c1; fa-chain</option>
                        <option value="fa-solid fa-check">&#xf00c; fa-check</option>
                        <option value="fa-solid fa-chevron-left">&#xf053; fa-chevron-left</option>
                        <option value="fa-solid fa-chevron-right">&#xf054; fa-chevron-right</option>
                        <option value="fa-solid fa-chevron-up">&#xf077; fa-chevron-up</option>
                        <option value="fa-solid fa-child">&#xf1ae; fa-child</option>
                        <option value="fa-solid fa-chrome">&#xf268; fa-chrome</option>
                        <option value="fa-solid fa-circle">&#xf111; fa-circle</option>
                        <option value="fa-solid fa-circle-o">&#xf10c; fa-circle-o</option>
                        <option value="fa-solid fa-circle-o-notch">&#xf1ce; fa-circle-o-notch</option>
                        <option value="fa-solid fa-circle-thin">&#xf1db; fa-circle-thin</option>
                        <option value="fa-solid fa-clipboard">&#xf0ea; fa-clipboard</option>
                        <option value="fa-solid fa-clock-o">&#xf017; fa-clock-o</option>
                        <option value="fa-solid fa-clone">&#xf24d; fa-clone</option>
                        <option value="fa-solid fa-close">&#xf00d; fa-close</option>
                        <option value="fa-solid fa-cloud">&#xf0c2; fa-cloud</option>
                        <option value="fa-solid fa-cloud-download">&#xf0ed; fa-cloud-download</option>
                        <option value="fa-solid fa-cloud-upload">&#xf0ee; fa-cloud-upload</option>
                        <option value="fa-solid fa-cny">&#xf157; fa-cny</option>
                        <option value="fa-solid fa-code">&#xf121; fa-code</option>
                        <option value="fa-solid fa-code-fork">&#xf126; fa-code-fork</option>
                        <option value="fa-solid fa-codepen">&#xf1cb; fa-codepen</option>
                        <option value="fa-solid fa-coffee">&#xf0f4; fa-coffee</option>
                        <option value="fa-solid fa-cog">&#xf013; fa-cog</option>
                        <option value="fa-solid fa-cogs">&#xf085; fa-cogs</option>
                        <option value="fa-solid fa-columns">&#xf0db; fa-columns</option>
                        <option value="fa-solid fa-comment">&#xf075; fa-comment</option>
                        <option value="fa-solid fa-comment-o">&#xf0e5; fa-comment-o</option>
                        <option value="fa-solid fa-commenting">&#xf27a; fa-commenting</option>
                        <option value="fa-solid fa-commenting-o">&#xf27b; fa-commenting-o</option>
                        <option value="fa-solid fa-comments">&#xf086; fa-comments</option>
                        <option value="fa-solid fa-comments-o">&#xf0e6; fa-comments-o</option>
                        <option value="fa-solid fa-compass">&#xf14e; fa-compass</option>
                        <option value="fa-solid fa-compress">&#xf066; fa-compress</option>
                        <option value="fa-solid fa-connectdevelop">&#xf20e; fa-connectdevelop</option>
                        <option value="fa-solid fa-contao">&#xf26d; fa-contao</option>
                        <option value="fa-solid fa-copy">&#xf0c5; fa-copy</option>
                        <option value="fa-solid fa-copyright">&#xf1f9; fa-copyright</option>
                        <option value="fa-solid fa-creative-commons">&#xf25e; fa-creative-commons</option>
                        <option value="fa-solid fa-credit-card">&#xf09d; fa-credit-card</option>
                        <option value="fa-solid fa-crop">&#xf125; fa-crop</option>
                        <option value="fa-solid fa-crosshairs">&#xf05b; fa-crosshairs</option>
                        <option value="fa-solid fa-css3">&#xf13c; fa-css3</option>
                        <option value="fa-solid fa-cube">&#xf1b2; fa-cube</option>
                        <option value="fa-solid fa-cubes">&#xf1b3; fa-cubes</option>
                        <option value="fa-solid fa-cut">&#xf0c4; fa-cut</option>
                        <option value="fa-solid fa-cutlery">&#xf0f5; fa-cutlery</option>
                        <option value="fa-solid fa-dashboard">&#xf0e4; fa-dashboard</option>
                        <option value="fa-solid fa-dashcube">&#xf210; fa-dashcube</option>
                        <option value="fa-solid fa-database">&#xf1c0; fa-database</option>
                        <option value="fa-solid fa-dedent">&#xf03b; fa-dedent</option>
                        <option value="fa-solid fa-delicious">&#xf1a5; fa-delicious</option>
                        <option value="fa-solid fa-desktop">&#xf108; fa-desktop</option>
                        <option value="fa-solid fa-deviantart">&#xf1bd; fa-deviantart</option>
                        <option value="fa-solid fa-diamond">&#xf219; fa-diamond</option>
                        <option value="fa-solid fa-digg">&#xf1a6; fa-digg</option>
                        <option value="fa-solid fa-dollar">&#xf155; fa-dollar</option>
                        <option value="fa-solid fa-download">&#xf019; fa-download</option>
                        <option value="fa-solid fa-dribbble">&#xf17d; fa-dribbble</option>
                        <option value="fa-solid fa-dropbox">&#xf16b; fa-dropbox</option>
                        <option value="fa-solid fa-drupal">&#xf1a9; fa-drupal</option>
                        <option value="fa-solid fa-edit">&#xf044; fa-edit</option>
                        <option value="fa-solid fa-eject">&#xf052; fa-eject</option>
                        <option value="fa-solid fa-ellipsis-h">&#xf141; fa-ellipsis-h</option>
                        <option value="fa-solid fa-ellipsis-v">&#xf142; fa-ellipsis-v</option>
                        <option value="fa-solid fa-empire">&#xf1d1; fa-empire</option>
                        <option value="fa-solid fa-envelope">&#xf0e0; fa-envelope</option>
                        <option value="fa-solid fa-envelope-o">&#xf003; fa-envelope-o</option>
                        <option value="fa-solid fa-eur">&#xf153; fa-eur</option>
                        <option value="fa-solid fa-euro">&#xf153; fa-euro</option>
                        <option value="fa-solid fa-exchange">&#xf0ec; fa-exchange</option>
                        <option value="fa-solid fa-exclamation">&#xf12a; fa-exclamation</option>
                        <option value="fa-solid fa-exclamation-circle">&#xf06a; fa-exclamation-circle</option>
                        <option value="fa-solid fa-exclamation-triangle">&#xf071; fa-exclamation-triangle</option>
                        <option value="fa-solid fa-expand">&#xf065; fa-expand</option>
                        <option value="fa-solid fa-expeditedssl">&#xf23e; fa-expeditedssl</option>
                        <option value="fa-solid fa-external-link">&#xf08e; fa-external-link</option>
                        <option value="fa-solid fa-external-link-square">&#xf14c; fa-external-link-square</option>
                        <option value="fa-solid fa-eye">&#xf06e; fa-eye</option>
                        <option value="fa-solid fa-eye-slash">&#xf070; fa-eye-slash</option>
                        <option value="fa-solid fa-eyedropper">&#xf1fb; fa-eyedropper</option>
                        <option value="fa-solid fa-facebook">&#xf09a; fa-facebook</option>
                        <option value="fa-solid fa-facebook-f">&#xf09a; fa-facebook-f</option>
                        <option value="fa-solid fa-facebook-official">&#xf230; fa-facebook-official</option>
                        <option value="fa-solid fa-facebook-square">&#xf082; fa-facebook-square</option>
                        <option value="fa-solid fa-fast-backward">&#xf049; fa-fast-backward</option>
                        <option value="fa-solid fa-fast-forward">&#xf050; fa-fast-forward</option>
                        <option value="fa-solid fa-fax">&#xf1ac; fa-fax</option>
                        <option value="fa-solid fa-feed">&#xf09e; fa-feed</option>
                        <option value="fa-solid fa-female">&#xf182; fa-female</option>
                        <option value="fa-solid fa-fighter-jet">&#xf0fb; fa-fighter-jet</option>
                        <option value="fa-solid fa-file">&#xf15b; fa-file</option>
                        <option value="fa-solid fa-file-archive-o">&#xf1c6; fa-file-archive-o</option>
                        <option value="fa-solid fa-file-audio-o">&#xf1c7; fa-file-audio-o</option>
                        <option value="fa-solid fa-file-code-o">&#xf1c9; fa-file-code-o</option>
                        <option value="fa-solid fa-file-excel-o">&#xf1c3; fa-file-excel-o</option>
                        <option value="fa-solid fa-file-image-o">&#xf1c5; fa-file-image-o</option>
                        <option value="fa-solid fa-file-movie-o">&#xf1c8; fa-file-movie-o</option>
                        <option value="fa-solid fa-file-o">&#xf016; fa-file-o</option>
                        <option value="fa-solid fa-file-pdf-o">&#xf1c1; fa-file-pdf-o</option>
                        <option value="fa-solid fa-file-photo-o">&#xf1c5; fa-file-photo-o</option>
                        <option value="fa-solid fa-file-picture-o">&#xf1c5; fa-file-picture-o</option>
                        <option value="fa-solid fa-file-powerpoint-o">&#xf1c4; fa-file-powerpoint-o</option>
                        <option value="fa-solid fa-file-sound-o">&#xf1c7; fa-file-sound-o</option>
                        <option value="fa-solid fa-file-text">&#xf15c; fa-file-text</option>
                        <option value="fa-solid fa-file-text-o">&#xf0f6; fa-file-text-o</option>
                        <option value="fa-solid fa-file-video-o">&#xf1c8; fa-file-video-o</option>
                        <option value="fa-solid fa-file-word-o">&#xf1c2; fa-file-word-o</option>
                        <option value="fa-solid fa-file-zip-o">&#xf1c6; fa-file-zip-o</option>
                        <option value="fa-solid fa-files-o">&#xf0c5; fa-files-o</option>
                        <option value="fa-solid fa-film">&#xf008; fa-film</option>
                        <option value="fa-solid fa-filter">&#xf0b0; fa-filter</option>
                        <option value="fa-solid fa-fire">&#xf06d; fa-fire</option>
                        <option value="fa-solid fa-fire-extinguisher">&#xf134; fa-fire-extinguisher</option>
                        <option value="fa-solid fa-firefox">&#xf269; fa-firefox</option>
                        <option value="fa-solid fa-flag">&#xf024; fa-flag</option>
                        <option value="fa-solid fa-flag-checkered">&#xf11e; fa-flag-checkered</option>
                        <option value="fa-solid fa-flag-o">&#xf11d; fa-flag-o</option>
                        <option value="fa-solid fa-flash">&#xf0e7; fa-flash</option>
                        <option value="fa-solid fa-flask">&#xf0c3; fa-flask</option>
                        <option value="fa-solid fa-flickr">&#xf16e; fa-flickr</option>
                        <option value="fa-solid fa-floppy-o">&#xf0c7; fa-floppy-o</option>
                        <option value="fa-solid fa-folder">&#xf07b; fa-folder</option>
                        <option value="fa-solid fa-folder-o">&#xf114; fa-folder-o</option>
                        <option value="fa-solid fa-folder-open">&#xf07c; fa-folder-open</option>
                        <option value="fa-solid fa-folder-open-o">&#xf115; fa-folder-open-o</option>
                        <option value="fa-solid fa-font">&#xf031; fa-font</option>
                        <option value="fa-solid fa-fonticons">&#xf280; fa-fonticons</option>
                        <option value="fa-solid fa-forumbee">&#xf211; fa-forumbee</option>
                        <option value="fa-solid fa-forward">&#xf04e; fa-forward</option>
                        <option value="fa-solid fa-foursquare">&#xf180; fa-foursquare</option>
                        <option value="fa-solid fa-frown-o">&#xf119; fa-frown-o</option>
                        <option value="fa-solid fa-futbol-o">&#xf1e3; fa-futbol-o</option>
                        <option value="fa-solid fa-gamepad">&#xf11b; fa-gamepad</option>
                        <option value="fa-solid fa-gavel">&#xf0e3; fa-gavel</option>
                        <option value="fa-solid fa-gbp">&#xf154; fa-gbp</option>
                        <option value="fa-solid fa-ge">&#xf1d1; fa-ge</option>
                        <option value="fa-solid fa-gear">&#xf013; fa-gear</option>
                        <option value="fa-solid fa-gears">&#xf085; fa-gears</option>
                        <option value="fa-solid fa-genderless">&#xf22d; fa-genderless</option>
                        <option value="fa-solid fa-get-pocket">&#xf265; fa-get-pocket</option>
                        <option value="fa-solid fa-gg">&#xf260; fa-gg</option>
                        <option value="fa-solid fa-gg-circle">&#xf261; fa-gg-circle</option>
                        <option value="fa-solid fa-gift">&#xf06b; fa-gift</option>
                        <option value="fa-solid fa-git">&#xf1d3; fa-git</option>
                        <option value="fa-solid fa-git-square">&#xf1d2; fa-git-square</option>
                        <option value="fa-solid fa-github">&#xf09b; fa-github</option>
                        <option value="fa-solid fa-github-alt">&#xf113; fa-github-alt</option>
                        <option value="fa-solid fa-github-square">&#xf092; fa-github-square</option>
                        <option value="fa-solid fa-gittip">&#xf184; fa-gittip</option>
                        <option value="fa-solid fa-glass">&#xf000; fa-glass</option>
                        <option value="fa-solid fa-globe">&#xf0ac; fa-globe</option>
                        <option value="fa-solid fa-google">&#xf1a0; fa-google</option>
                        <option value="fa-solid fa-google-plus">&#xf0d5; fa-google-plus</option>
                        <option value="fa-solid fa-google-plus-square">&#xf0d4; fa-google-plus-square</option>
                        <option value="fa-solid fa-google-wallet">&#xf1ee; fa-google-wallet</option>
                        <option value="fa-solid fa-graduation-cap">&#xf19d; fa-graduation-cap</option>
                        <option value="fa-solid fa-gratipay">&#xf184; fa-gratipay</option>
                        <option value="fa-solid fa-group">&#xf0c0; fa-group</option>
                        <option value="fa-solid fa-h-square">&#xf0fd; fa-h-square</option>
                        <option value="fa-solid fa-hacker-news">&#xf1d4; fa-hacker-news</option>
                        <option value="fa-solid fa-hand-grab-o">&#xf255; fa-hand-grab-o</option>
                        <option value="fa-solid fa-hand-lizard-o">&#xf258; fa-hand-lizard-o</option>
                        <option value="fa-solid fa-hand-o-down">&#xf0a7; fa-hand-o-down</option>
                        <option value="fa-solid fa-hand-o-left">&#xf0a5; fa-hand-o-left</option>
                        <option value="fa-solid fa-hand-o-right">&#xf0a4; fa-hand-o-right</option>
                        <option value="fa-solid fa-hand-o-up">&#xf0a6; fa-hand-o-up</option>
                        <option value="fa-solid fa-hand-paper-o">&#xf256; fa-hand-paper-o</option>
                        <option value="fa-solid fa-hand-peace-o">&#xf25b; fa-hand-peace-o</option>
                        <option value="fa-solid fa-hand-pointer-o">&#xf25a; fa-hand-pointer-o</option>
                        <option value="fa-solid fa-hand-rock-o">&#xf255; fa-hand-rock-o</option>
                        <option value="fa-solid fa-hand-scissors-o">&#xf257; fa-hand-scissors-o</option>
                        <option value="fa-solid fa-hand-spock-o">&#xf259; fa-hand-spock-o</option>
                        <option value="fa-solid fa-hand-stop-o">&#xf256; fa-hand-stop-o</option>
                        <option value="fa-solid fa-hdd-o">&#xf0a0; fa-hdd-o</option>
                        <option value="fa-solid fa-header">&#xf1dc; fa-header</option>
                        <option value="fa-solid fa-headphones">&#xf025; fa-headphones</option>
                        <option value="fa-solid fa-heart">&#xf004; fa-heart</option>
                        <option value="fa-solid fa-heart-o">&#xf08a; fa-heart-o</option>
                        <option value="fa-solid fa-heartbeat">&#xf21e; fa-heartbeat</option>
                        <option value="fa-solid fa-history">&#xf1da; fa-history</option>
                        <option value="fa-solid fa-home">&#xf015; fa-home</option>
                        <option value="fa-solid fa-hospital-o">&#xf0f8; fa-hospital-o</option>
                        <option value="fa-solid fa-hotel">&#xf236; fa-hotel</option>
                        <option value="fa-solid fa-hourglass">&#xf254; fa-hourglass</option>
                        <option value="fa-solid fa-hourglass-1">&#xf251; fa-hourglass-1</option>
                        <option value="fa-solid fa-hourglass-2">&#xf252; fa-hourglass-2</option>
                        <option value="fa-solid fa-hourglass-3">&#xf253; fa-hourglass-3</option>
                        <option value="fa-solid fa-hourglass-end">&#xf253; fa-hourglass-end</option>
                        <option value="fa-solid fa-hourglass-half">&#xf252; fa-hourglass-half</option>
                        <option value="fa-solid fa-hourglass-o">&#xf250; fa-hourglass-o</option>
                        <option value="fa-solid fa-hourglass-start">&#xf251; fa-hourglass-start</option>
                        <option value="fa-solid fa-houzz">&#xf27c; fa-houzz</option>
                        <option value="fa-solid fa-html5">&#xf13b; fa-html5</option>
                        <option value="fa-solid fa-i-cursor">&#xf246; fa-i-cursor</option>
                        <option value="fa-solid fa-ils">&#xf20b; fa-ils</option>
                        <option value="fa-solid fa-image">&#xf03e; fa-image</option>
                        <option value="fa-solid fa-inbox">&#xf01c; fa-inbox</option>
                        <option value="fa-solid fa-indent">&#xf03c; fa-indent</option>
                        <option value="fa-solid fa-industry">&#xf275; fa-industry</option>
                        <option value="fa-solid fa-info">&#xf129; fa-info</option>
                        <option value="fa-solid fa-info-circle">&#xf05a; fa-info-circle</option>
                        <option value="fa-solid fa-inr">&#xf156; fa-inr</option>
                        <option value="fa-solid fa-instagram">&#xf16d; fa-instagram</option>
                        <option value="fa-solid fa-institution">&#xf19c; fa-institution</option>
                        <option value="fa-solid fa-internet-explorer">&#xf26b; fa-internet-explorer</option>
                        <option value="fa-solid fa-intersex">&#xf224; fa-intersex</option>
                        <option value="fa-solid fa-ioxhost">&#xf208; fa-ioxhost</option>
                        <option value="fa-solid fa-italic">&#xf033; fa-italic</option>
                        <option value="fa-solid fa-joomla">&#xf1aa; fa-joomla</option>
                        <option value="fa-solid fa-jpy">&#xf157; fa-jpy</option>
                        <option value="fa-solid fa-jsfiddle">&#xf1cc; fa-jsfiddle</option>
                        <option value="fa-solid fa-key">&#xf084; fa-key</option>
                        <option value="fa-solid fa-keyboard-o">&#xf11c; fa-keyboard-o</option>
                        <option value="fa-solid fa-krw">&#xf159; fa-krw</option>
                        <option value="fa-solid fa-language">&#xf1ab; fa-language</option>
                        <option value="fa-solid fa-laptop">&#xf109; fa-laptop</option>
                        <option value="fa-solid fa-lastfm">&#xf202; fa-lastfm</option>
                        <option value="fa-solid fa-lastfm-square">&#xf203; fa-lastfm-square</option>
                        <option value="fa-solid fa-leaf">&#xf06c; fa-leaf</option>
                        <option value="fa-solid fa-leanpub">&#xf212; fa-leanpub</option>
                        <option value="fa-solid fa-legal">&#xf0e3; fa-legal</option>
                        <option value="fa-solid fa-lemon-o">&#xf094; fa-lemon-o</option>
                        <option value="fa-solid fa-level-down">&#xf149; fa-level-down</option>
                        <option value="fa-solid fa-level-up">&#xf148; fa-level-up</option>
                        <option value="fa-solid fa-life-bouy">&#xf1cd; fa-life-bouy</option>
                        <option value="fa-solid fa-life-buoy">&#xf1cd; fa-life-buoy</option>
                        <option value="fa-solid fa-life-ring">&#xf1cd; fa-life-ring</option>
                        <option value="fa-solid fa-life-saver">&#xf1cd; fa-life-saver</option>
                        <option value="fa-solid fa-lightbulb-o">&#xf0eb; fa-lightbulb-o</option>
                        <option value="fa-solid fa-line-chart">&#xf201; fa-line-chart</option>
                        <option value="fa-solid fa-link">&#xf0c1; fa-link</option>
                        <option value="fa-solid fa-linkedin">&#xf0e1; fa-linkedin</option>
                        <option value="fa-solid fa-linkedin-square">&#xf08c; fa-linkedin-square</option>
                        <option value="fa-solid fa-linux">&#xf17c; fa-linux</option>
                        <option value="fa-solid fa-list">&#xf03a; fa-list</option>
                        <option value="fa-solid fa-list-alt">&#xf022; fa-list-alt</option>
                        <option value="fa-solid fa-list-ol">&#xf0cb; fa-list-ol</option>
                        <option value="fa-solid fa-list-ul">&#xf0ca; fa-list-ul</option>
                        <option value="fa-solid fa-location-arrow">&#xf124; fa-location-arrow</option>
                        <option value="fa-solid fa-lock">&#xf023; fa-lock</option>
                        <option value="fa-solid fa-long-arrow-down">&#xf175; fa-long-arrow-down</option>
                        <option value="fa-solid fa-long-arrow-left">&#xf177; fa-long-arrow-left</option>
                        <option value="fa-solid fa-long-arrow-right">&#xf178; fa-long-arrow-right</option>
                        <option value="fa-solid fa-long-arrow-up">&#xf176; fa-long-arrow-up</option>
                        <option value="fa-solid fa-magic">&#xf0d0; fa-magic</option>
                        <option value="fa-solid fa-magnet">&#xf076; fa-magnet</option>
                        <option value="fa-solid fa-mars-stroke-v">&#xf22a; fa-mars-stroke-v</option>
                        <option value="fa-solid fa-maxcdn">&#xf136; fa-maxcdn</option>
                        <option value="fa-solid fa-meanpath">&#xf20c; fa-meanpath</option>
                        <option value="fa-solid fa-medium">&#xf23a; fa-medium</option>
                        <option value="fa-solid fa-medkit">&#xf0fa; fa-medkit</option>
                        <option value="fa-solid fa-meh-o">&#xf11a; fa-meh-o</option>
                        <option value="fa-solid fa-mercury">&#xf223; fa-mercury</option>
                        <option value="fa-solid fa-microphone">&#xf130; fa-microphone</option>
                        <option value="fa-solid fa-mobile">&#xf10b; fa-mobile</option>
                        <option value="fa-solid fa-motorcycle">&#xf21c; fa-motorcycle</option>
                        <option value="fa-solid fa-mouse-pointer">&#xf245; fa-mouse-pointer</option>
                        <option value="fa-solid fa-music">&#xf001; fa-music</option>
                        <option value="fa-solid fa-navicon">&#xf0c9; fa-navicon</option>
                        <option value="fa-solid fa-neuter">&#xf22c; fa-neuter</option>
                        <option value="fa-solid fa-newspaper-o">&#xf1ea; fa-newspaper-o</option>
                        <option value="fa-solid fa-opencart">&#xf23d; fa-opencart</option>
                        <option value="fa-solid fa-openid">&#xf19b; fa-openid</option>
                        <option value="fa-solid fa-opera">&#xf26a; fa-opera</option>
                        <option value="fa-solid fa-outdent">&#xf03b; fa-outdent</option>
                        <option value="fa-solid fa-pagelines">&#xf18c; fa-pagelines</option>
                        <option value="fa-solid fa-paper-plane-o">&#xf1d9; fa-paper-plane-o</option>
                        <option value="fa-solid fa-paperclip">&#xf0c6; fa-paperclip</option>
                        <option value="fa-solid fa-paragraph">&#xf1dd; fa-paragraph</option>
                        <option value="fa-solid fa-paste">&#xf0ea; fa-paste</option>
                        <option value="fa-solid fa-pause">&#xf04c; fa-pause</option>
                        <option value="fa-solid fa-paw">&#xf1b0; fa-paw</option>
                        <option value="fa-solid fa-paypal">&#xf1ed; fa-paypal</option>
                        <option value="fa-solid fa-pencil">&#xf040; fa-pencil</option>
                        <option value="fa-solid fa-pencil-square-o">&#xf044; fa-pencil-square-o</option>
                        <option value="fa-solid fa-phone">&#xf095; fa-phone</option>
                        <option value="fa-solid fa-photo">&#xf03e; fa-photo</option>
                        <option value="fa-solid fa-picture-o">&#xf03e; fa-picture-o</option>
                        <option value="fa-solid fa-pie-chart">&#xf200; fa-pie-chart</option>
                        <option value="fa-solid fa-pied-piper">&#xf1a7; fa-pied-piper</option>
                        <option value="fa-solid fa-pied-piper-alt">&#xf1a8; fa-pied-piper-alt</option>
                        <option value="fa-solid fa-pinterest">&#xf0d2; fa-pinterest</option>
                        <option value="fa-solid fa-pinterest-p">&#xf231; fa-pinterest-p</option>
                        <option value="fa-solid fa-pinterest-square">&#xf0d3; fa-pinterest-square</option>
                        <option value="fa-solid fa-plane">&#xf072; fa-plane</option>
                        <option value="fa-solid fa-play">&#xf04b; fa-play</option>
                        <option value="fa-solid fa-play-circle">&#xf144; fa-play-circle</option>
                        <option value="fa-solid fa-play-circle-o">&#xf01d; fa-play-circle-o</option>
                        <option value="fa-solid fa-plug">&#xf1e6; fa-plug</option>
                        <option value="fa-solid fa-plus">&#xf067; fa-plus</option>
                        <option value="fa-solid fa-plus-circle">&#xf055; fa-plus-circle</option>
                        <option value="fa-solid fa-plus-square">&#xf0fe; fa-plus-square</option>
                        <option value="fa-solid fa-plus-square-o">&#xf196; fa-plus-square-o</option>
                        <option value="fa-solid fa-power-off">&#xf011; fa-power-off</option>
                        <option value="fa-solid fa-print">&#xf02f; fa-print</option>
                        <option value="fa-solid fa-puzzle-piece">&#xf12e; fa-puzzle-piece</option>
                        <option value="fa-solid fa-qq">&#xf1d6; fa-qq</option>
                        <option value="fa-solid fa-qrcode">&#xf029; fa-qrcode</option>
                        <option value="fa-solid fa-question">&#xf128; fa-question</option>
                        <option value="fa-solid fa-question-circle">&#xf059; fa-question-circle</option>
                        <option value="fa-solid fa-quote-left">&#xf10d; fa-quote-left</option>
                        <option value="fa-solid fa-quote-right">&#xf10e; fa-quote-right</option>
                        <option value="fa-solid fa-ra">&#xf1d0; fa-ra</option>
                        <option value="fa-solid fa-random">&#xf074; fa-random</option>
                        <option value="fa-solid fa-rebel">&#xf1d0; fa-rebel</option>
                        <option value="fa-solid fa-recycle">&#xf1b8; fa-recycle</option>
                        <option value="fa-solid fa-reddit">&#xf1a1; fa-reddit</option>
                        <option value="fa-solid fa-reddit-square">&#xf1a2; fa-reddit-square</option>
                        <option value="fa-solid fa-refresh">&#xf021; fa-refresh</option>
                        <option value="fa-solid fa-registered">&#xf25d; fa-registered</option>
                        <option value="fa-solid fa-remove">&#xf00d; fa-remove</option>
                        <option value="fa-solid fa-renren">&#xf18b; fa-renren</option>
                        <option value="fa-solid fa-reorder">&#xf0c9; fa-reorder</option>
                        <option value="fa-solid fa-repeat">&#xf01e; fa-repeat</option>
                        <option value="fa-solid fa-reply">&#xf112; fa-reply</option>
                        <option value="fa-solid fa-reply-all">&#xf122; fa-reply-all</option>
                        <option value="fa-solid fa-retweet">&#xf079; fa-retweet</option>
                        <option value="fa-solid fa-rmb">&#xf157; fa-rmb</option>
                        <option value="fa-solid fa-road">&#xf018; fa-road</option>
                        <option value="fa-solid fa-rocket">&#xf135; fa-rocket</option>
                        <option value="fa-solid fa-rotate-left">&#xf0e2; fa-rotate-left</option>
                        <option value="fa-solid fa-rotate-right">&#xf01e; fa-rotate-right</option>
                        <option value="fa-solid fa-rouble">&#xf158; fa-rouble</option>
                        <option value="fa-solid fa-rss">&#xf09e; fa-rss</option>
                        <option value="fa-solid fa-rss-square">&#xf143; fa-rss-square</option>
                        <option value="fa-solid fa-rub">&#xf158; fa-rub</option>
                        <option value="fa-solid fa-ruble">&#xf158; fa-ruble</option>
                        <option value="fa-solid fa-rupee">&#xf156; fa-rupee</option>
                        <option value="fa-solid fa-safari">&#xf267; fa-safari</option>
                        <option value="fa-solid fa-sliders">&#xf1de; fa-sliders</option>
                        <option value="fa-solid fa-slideshare">&#xf1e7; fa-slideshare</option>
                        <option value="fa-solid fa-smile-o">&#xf118; fa-smile-o</option>
                        <option value="fa-solid fa-sort-asc">&#xf0de; fa-sort-asc</option>
                        <option value="fa-solid fa-sort-desc">&#xf0dd; fa-sort-desc</option>
                        <option value="fa-solid fa-sort-down">&#xf0dd; fa-sort-down</option>
                        <option value="fa-solid fa-spinner">&#xf110; fa-spinner</option>
                        <option value="fa-solid fa-spoon">&#xf1b1; fa-spoon</option>
                        <option value="fa-solid fa-spotify">&#xf1bc; fa-spotify</option>
                        <option value="fa-solid fa-square">&#xf0c8; fa-square</option>
                        <option value="fa-solid fa-square-o">&#xf096; fa-square-o</option>
                        <option value="fa-solid fa-star">&#xf005; fa-star</option>
                        <option value="fa-solid fa-star-half">&#xf089; fa-star-half</option>
                        <option value="fa-solid fa-stop">&#xf04d; fa-stop</option>
                        <option value="fa-solid fa-subscript">&#xf12c; fa-subscript</option>
                        <option value="fa-solid fa-tablet">&#xf10a; fa-tablet</option>
                        <option value="fa-solid fa-tachometer">&#xf0e4; fa-tachometer</option>
                        <option value="fa-solid fa-tag">&#xf02b; fa-tag</option>
                        <option value="fa-solid fa-tags">&#xf02c; fa-tags</option>
                    </select>
                    @error('icon')
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
@endsection

<style scoped>
    select {
        font-family: 'FontAwesome', 'sans-serif' !important;
    }
</style>
